language: php

# The platforms you wants to test on
dist: trusty
os:
  - linux

# Install google chrome latest stable
addons:
  apt:
    packages:
      - google-chrome-stable

# git configs
git:
  depth: 1

php:
  - 5.6
  - 7.0
  - 7.1
matrix:
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

services: mysql

before_install:
  - phpenv config-rm xdebug.ini # Disable x-debug to speed up things
  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
install:
  #- wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  #- unzip chromedriver_linux64.zip -d ./
  #- export CHROME_BIN=chromium-browser
  # Start xvfb for gui test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # Download and start selenium
  - echo "Download selenium-server-standalone jar file"
  - wget -c -nc --retry-connrefused --tries=0 https://goo.gl/s4o9Vx -O selenium-server-standalone.jar
  - echo "Download chrome driver and unzip it"
  - wget -c -nc --retry-connrefused --tries=0 http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
  - unzip -o -q chromedriver_linux64.zip
  - echo "Run selenium server - background process"
  - nohup bash -c "java -jar selenium-server-standalone.jar &" && sleep 1; cat nohup.out
  - ls -al

  # Run Composer update
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.3"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry composer global require "codeception/codeception=2.3.*" "codeception/specify=*" "codeception/verify=*"
  # Install test environment
  - |
    mysql -e 'CREATE DATABASE `humhub_test` CHARACTER SET utf8 COLLATE utf8_general_ci;'
    cd protected/humhub/tests/codeception/bin
    php yii migrate/up --includeModuleMigrations=1 --interactive=0
    php yii installer/auto
    php yii search/rebuild
    cd ../../../../..
    cd protected/humhub/tests
    codecept build
    cd ../../../

script:
  - php -S 127.0.0.1:8080 > /dev/null 2>&1 &
  - sleep 5
  - curl http://127.0.0.1:8080/index-test.php
  - |
    cd protected/humhub/tests/
    codecept run --env chrome
after_failure:
  - cd ../modules/user/tests/codeception/_output/
  - ls
  - cat ../modules/*/tests/codeception/_output/*.html

